### ISSUE TITLE
TaskMaybe and composability

### ISSUE THREAD

**Issue by ladeak** [ploeh/asynchronous-injection#2]
Isn't TaskMaybe against composability? I would like to be able to compose a Task and Maybe together, so Task does not need to know about Maybe, and Maybe does not need to know about Task.

**Comment by ploeh** [comment]
I'm sorry, I don't understand the question.

> I would like to be able to compose a Task and Maybe together [...]

Could you provide an example?

**Comment by ladeak** [comment]
So my question is: is it possible to achieve the same type of chaining:
```csharp
return await Repository.ReadReservations(reservation.Date)
            .Select(rs => maîtreD.TryAccept(rs, reservation))
            .SelectMany(m => m.Traverse(Repository.Create))
            .Match(InternalServerError("Table unavailable"), Ok);
```

Without having to write extension methods on Task<Maybe<T>> type?
Otherwise, would I write an extension method to all functors? (Maybe, Either, etc.)

**Comment by ploeh** [comment]
If that's possible, I don't know how to do it.

Those extension methods enable the desired functionality for the types in question. If you own the type in question, the methods can also be instance methods; they don't _have_ to be extension methods. That's the case for `Maybe<T>`.
